services:
  - name: attendance-app
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 main:app
    envVars:
      - key: FLASK_ENV
        value: production
